[build]
  base    = "packages/web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
