-- Supabase schema for FinanceTracker

-- users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  email text unique,
  password text,
  country text,
  created_at timestamp with time zone default now()
);

-- transactions
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade,
  type text not null,
  name text,
  category text,
  amount numeric,
  date timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- RPC function to sum by type
create or replace function public.sum_transactions_by_type(p_user_id bigint, p_type text)
returns table(sum numeric) language sql as $$
  select coalesce(sum(amount), 0) as sum from transactions where user_id = p_user_id and type = p_type;
$$;
